language: node_js

node_js:
- "0.10"

before_install:
  - sudo add-apt-repository ppa:fkrull/deadsnakes -y
  - sudo apt-get update
  - sudo apt-get install python3.3

install:
  - python3.3 --version
  - node --version
  - npm install -g brunch

script: "python3.3 test_skeleton.py" 
